# Generated by Django 4.2.7 on 2023-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='file',
            field=models.FileField(blank=True, upload_to='training_files/'),
        ),
    ]
